import {DEVICE_TASK_KINDS,DEVICE_STATES} from './device-task-model.mjs?v=bridge-1';
import {escapeHtml as e} from './recommendation-model.mjs?v=bridge-1';
export function deviceTaskEditor(policy,base){
  const task=policy.deviceTask;
  if(!task?.enabled)return `<button class="button secondary" type="button" data-add-device="${base}">Add a California water-shutoff next step</button>`;
  const path=`${base}.deviceTask`;
  return `<details class="source-details" open><summary>Device-related next step · this policy only</summary><p>California automatic water shutoff pilot. A discount reference is not a requirement. Confirm the exact case and timing; never infer either from the carrier name.</p><label for="${path}-kind">Classification</label><select id="${path}-kind" data-field="${path}.kind">${Object.entries(DEVICE_TASK_KINDS).map(([id,label])=>`<option value="${id}" ${task.kind===id?'selected':''}>${label}</option>`).join('')}</select><label for="${path}-source">Private case-specific source / reference</label><textarea id="${path}-source" data-field="${path}.sourceNote" maxlength="700">${e(task.sourceNote||'')}</textarea><label for="${path}-instruction">Customer’s next action (no private policy details)</label><textarea id="${path}-instruction" data-field="${path}.instruction" maxlength="400">${e(task.instruction||'')}</textarea><label for="${path}-due">Documented due date, if applicable</label><input id="${path}-due" type="date" data-field="${path}.dueDate" value="${e(task.dueDate||'')}"><label class="check"><input type="checkbox" data-field="${path}.confirmed" ${task.confirmed?'checked':''}>I confirmed the case-specific classification, source, action and timing. This does not record carrier acceptance of a product.</label><button class="button quiet" type="button" data-remove-device="${base}">Remove device task from this draft</button></details>`;
}
export function deviceCards(option,data){return option.policies.filter(p=>p.deviceTask?.enabled).map(policy=>{
  const task=policy.deviceTask,update=(data.deviceUpdates||[]).find(u=>u.option_id===option.id&&u.policy_id===policy.id),blocked=data.superseded||(data.quoteExpired&&!(task.kind==='after-binding'&&data.producerRecordedBoundPolicyIds?.includes(policy.id)));
  return `<section class="card device-task-card" aria-label="Device-related next step"><p class="eyebrow">${e(policy.carrier)} · ${e(policy.product)}</p><h2>Your water-protection next step</h2><p><strong>${e(DEVICE_TASK_KINDS[task.kind])}</strong></p><p>${e(task.instruction)}</p>${task.dueDate?`<p>Documented due date: <strong>${e(task.dueDate)}</strong></p>`:''}<p class="muted">Equipment, installation and subscriptions are separate from your insurance premium. Selecting a device does not confirm suitability or insurer acceptance.</p>${update?`<p class="notice success">${e(DEVICE_STATES[update.payload.state]||'Customer update received')}${update.payload.deviceId?` · ${e(update.payload.deviceId)}`:''}. Saved to this review. Professional review remains separate.</p>`:''}${!blocked&&data.deviceBridgeEnabled?`<button class="button secondary" type="button" data-device-policy="${e(policy.id)}">Review device options or report an existing system</button><div id="device-consent-${e(policy.id)}" hidden><p>SmartDevices is independent. Share only the device capability, California scope, task classification and policy type/carrier. Your name, contact details, premium and quote documents are not sent. Device choices are sent back only when you explicitly save an update.</p><button class="button secondary" type="button" data-device-launch="${e(policy.id)}">Continue to SmartDevices</button></div>`:`<p>Ask Dylan to confirm this device step. Your insurance review, question and proceed actions remain available for the current quote.</p>`}<p id="device-status-${e(policy.id)}" role="status"></p></section>`;
}).join('');}
export function returnContext(){
  const params=new URLSearchParams(location.hash.slice(1)),key=params.get('deviceReturn');
  if(!key||!/^[A-Za-z0-9_-]{43}$/.test(key))return null;
  try{const saved=JSON.parse(sessionStorage.getItem(`cf-device-return-${key}`)||'null');if(saved&&/^[A-Za-z0-9_-]{43}$/.test(saved.token||'')&&Date.now()-saved.at<24*60*60*1000){history.replaceState(null,'',`/review/#t=${saved.token}`);return saved;}}catch{}
  return null;
}
