import {bridgeConfig,deviceSignature,digest,deviceFail} from './device-task-bridge.mjs';
import {listProtectionPresets} from './protection-presets.mjs';
import {policyTasks,PROTECTIONS,PROTECTION_STATES,DEFAULT_PRESETS,currentPreset,stateAllowed,CONTRACTOR_LINKS} from '../assets/js/protection-model.mjs';
const UUID=/^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/i;
function scope(record,revision,optionId,policyId){
 if(!revision||revision.revoked_at||Date.parse(revision.expires_at)<=Date.now())deviceFail(410,'review_expired','Reopen the current insurance review.');
 if(record.current_revision!==revision.revision)deviceFail(409,'superseded','The recommendation changed. Reopen the latest review.');
 const option=revision.payload.options.find(o=>o.id===optionId),policy=option?.policies.find(p=>p.id===policyId);
 if(!policy||!policyTasks(policy).length)deviceFail(404,'protection_scope','This policy has no protection recommendations.');
 return {option,policy,tasks:policyTasks(policy)};
}
function timingAllowed(record,option,policy,task){const today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Los_Angeles',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());return !option.policies.some(p=>p.quoteExpiresOn&&p.quoteExpiresOn<today)||(task.kind==='after-binding'&&['bound','partial'].includes(record.outcome?.kind)&&record.outcome.policyIds?.includes(policy.id));}
export async function launchProtection(client,value,opts){
 const config=bridgeConfig(opts.env),{record,revision}=client,{option,policy,tasks}=scope(record,revision,value.optionId,value.policyId),task=tasks.find(t=>t.id===value.taskId);
 if(!task)deviceFail(404,'protection_scope','Choose a protection step attached to this policy.');
 if(!timingAllowed(record,option,policy,task))deviceFail(409,'quote_expired','Ask Dylan to confirm the current quote before continuing.');
 if(value.consent!==true)deviceFail(422,'device_consent','Confirm the limited context you want to share.');
 const token=btoa(String.fromCharCode(...crypto.getRandomValues(new Uint8Array(32)))).replaceAll('+','-').replaceAll('/','_').replaceAll('=',''),expiresAt=new Date(Date.now()+3600000).toISOString();
 await opts.db.prepare('INSERT INTO cf_protection_sessions(token_hash,recommendation_id,revision,option_id,policy_id,initial_task_id,expires_at) VALUES(?1,?2,?3,?4,?5,?6,?7)').bind(await digest(token),record.id,revision.revision,option.id,policy.id,task.id,expiresAt).run();
 return {ok:true,launchUrl:`${config.origin}/insurance-task#h=${token}&v=2`,returnKey:token,expiresAt};
}
async function signedBody(request,raw,opts){const {secret}=bridgeConfig(opts.env),timestamp=request.headers.get('x-device-timestamp')||'',nonce=request.headers.get('x-device-nonce')||'',signature=request.headers.get('x-device-signature')||'';
 if(!/^\d{13}$/.test(timestamp)||Math.abs(Date.now()-Number(timestamp))>120000||!UUID.test(nonce)||!/^[a-f0-9]{64}$/.test(signature))deviceFail(403,'device_auth','The connection could not be verified.');
 const expected=await deviceSignature(secret,`${timestamp}\n${nonce}\n${raw}`);let diff=0;for(let i=0;i<64;i++)diff|=signature.charCodeAt(i)^expected.charCodeAt(i);if(diff)deviceFail(403,'device_auth','The connection could not be verified.');
 const value=JSON.parse(raw);if(value?.bridgeVersion!==2||!['read','save'].includes(value.operation)||!/^[A-Za-z0-9_-]{43}$/.test(value.token||''))deviceFail(422,'device_request','Invalid protection request.');
 const result=await opts.db.prepare('INSERT OR IGNORE INTO cf_device_nonces(nonce,expires_at) VALUES(?1,?2)').bind(nonce,new Date(Date.now()+300000).toISOString()).run();if(result.meta?.changes!==1)deviceFail(409,'device_replay','Retry with a fresh connection request.');return value;
}
const latestSql='SELECT * FROM cf_protection_updates WHERE recommendation_id=?1 AND revision=?2 AND option_id=?3 AND policy_id=?4 AND task_id=?5 ORDER BY sequence DESC LIMIT 1';
async function projection(task,catalog,record,option,policy,opts,revision){
 const recommended=task.recommendation||DEFAULT_PRESETS.find(p=>p.id===task.presetId&&p.category===task.id),live=catalog.find(p=>p.id===task.presetId&&p.category===task.id);
 const current=!!recommended&&!!live&&currentPreset(recommended)&&currentPreset(live)&&live.version===recommended.version;
 const latest=await opts.db.prepare(latestSql).bind(record.id,revision.revision,option.id,policy.id,task.id).first();
 return {id:task.id,label:PROTECTIONS[task.id],capability:task.capability,jurisdiction:'CA',kind:task.kind,dueDate:task.dueDate,assertionSource:'professional-stated-unverified',recommendation:recommended?{id:recommended.id,version:recommended.version,provider:recommended.provider,title:recommended.title,url:current?recommended.url:'',monitoringUrl:current?recommended.monitoringUrl:'',setup:recommended.setup,documentation:recommended.documentation,costNote:recommended.costNote,checkedAt:recommended.checkedAt,reviewDue:recommended.reviewDue}:null,current,canUpdate:timingAllowed(record,option,policy,task),contractorLinks:task.id==='gas'?CONTRACTOR_LINKS:[],version:latest?.sequence||0,progress:latest?JSON.parse(latest.payload_json):null};
}
export async function protectionBridge(request,raw,opts){
 const value=await signedBody(request,raw,opts),session=await opts.db.prepare('SELECT * FROM cf_protection_sessions WHERE token_hash=?1').bind(await digest(value.token)).first();
 if(!session||Date.parse(session.expires_at)<=Date.now())deviceFail(410,'device_expired','Reopen protection guidance from your insurance review.');
 const record=await opts.repo.get(session.recommendation_id),revision=await opts.repo.revision(session.recommendation_id,session.revision);if(!record)deviceFail(410,'device_expired','This review is unavailable.');
 const {option,policy,tasks}=scope(record,revision,session.option_id,session.policy_id),catalog=await listProtectionPresets(opts.db,record.owner_id);
 if(value.operation==='read'){const visible=[];for(const task of tasks)visible.push(await projection(task,catalog,record,option,policy,opts,revision));return {ok:true,bridgeVersion:2,activeTaskId:session.initial_task_id,tasks:visible,policy:{carrier:policy.carrier,product:policy.product},expiresAt:session.expires_at};}
 const task=tasks.find(t=>t.id===value.taskId);if(!task)deviceFail(404,'protection_scope','This protection step is not attached to the policy.');
 if(!timingAllowed(record,option,policy,task))deviceFail(409,'quote_expired','Return to Dylan for a current quote.');
 if(value.consent!==true||!UUID.test(value.requestId||'')||!Number.isInteger(value.expectedVersion)||value.expectedVersion<0||!stateAllowed(task.id,value.state))deviceFail(422,'device_update','Confirm a supported update and permission to share it.');
 const visible=await projection(task,catalog,record,option,policy,opts,revision),deviceId=value.deviceId||'';
 if(deviceId&&(deviceId!==task.presetId||!visible.current))deviceFail(409,'preset_unavailable','This recommendation needs review. You can still report an existing system or ask for help.');
 if(value.state==='considering'&&!deviceId)deviceFail(422,'device_model','Choose the recommended setup or ask your agent for help.');
 const payload={state:value.state,deviceId,taskId:task.id,assertionSource:'consumer-self-reported',consentPurpose:'insurance-protection-task-update'};
 let saved=await opts.db.prepare('SELECT * FROM cf_protection_updates WHERE request_id=?1').bind(value.requestId).first();
 if(saved&&(saved.recommendation_id!==record.id||saved.revision!==revision.revision||saved.option_id!==option.id||saved.policy_id!==policy.id||saved.task_id!==task.id||saved.payload_json!==JSON.stringify(payload)))deviceFail(409,'device_idempotency','This update identifier was used for a different action. Reload the saved update.');
 if(!saved){if(value.expectedVersion!==visible.version)deviceFail(409,'device_conflict','This protection step changed elsewhere. Reload before saving.');try{await opts.db.prepare('INSERT INTO cf_protection_updates(request_id,recommendation_id,revision,option_id,policy_id,task_id,sequence,payload_json,created_at) VALUES(?1,?2,?3,?4,?5,?6,?7,?8,?9)').bind(value.requestId,record.id,revision.revision,option.id,policy.id,task.id,visible.version+1,JSON.stringify(payload),new Date().toISOString()).run();}catch{deviceFail(409,'device_conflict','Another update may have arrived. Reload before saving.');}saved={sequence:visible.version+1};}
 const event=await opts.repo.event(record.id,revision.revision,'device_update',`protection:${value.requestId}`,{...payload,bridgeVersion:2,optionId:option.id,policyId:policy.id,updateRequestId:value.requestId,message:`${PROTECTIONS[task.id]}: ${PROTECTION_STATES[value.state]}. Professional review and insurer acceptance remain separate.`});
 return {ok:true,bridgeVersion:2,saved:true,taskId:task.id,version:saved.sequence,progress:payload,event};
}
export async function protectionClientContext(opts,record,revisionRecord){const id=record.id,revision=revisionRecord.revision;if(opts.env.COVERAGEFIT_SMARTDEVICES_ENABLED!=='true')return {protectionBridgeEnabled:false,protectionUpdates:[]};try{bridgeConfig(opts.env);const rows=await opts.db.prepare('SELECT * FROM cf_protection_updates u WHERE recommendation_id=?1 AND revision=?2 AND sequence=(SELECT MAX(u2.sequence) FROM cf_protection_updates u2 WHERE u2.recommendation_id=u.recommendation_id AND u2.revision=u.revision AND u2.option_id=u.option_id AND u2.policy_id=u.policy_id AND u2.task_id=u.task_id) ORDER BY created_at DESC LIMIT 96').bind(id,revision).all();const catalog=await listProtectionPresets(opts.db,record.owner_id),protectionAvailability=[];for(const option of revisionRecord.payload.options)for(const policy of option.policies)for(const task of policyTasks(policy)){const live=catalog.find(p=>p.id===task.presetId),snapshot=task.recommendation||DEFAULT_PRESETS.find(p=>p.id===task.presetId);protectionAvailability.push({optionId:option.id,policyId:policy.id,taskId:task.id,current:!!live&&!!snapshot&&currentPreset(live)&&currentPreset(snapshot)&&live.version===snapshot.version});}return {protectionBridgeEnabled:true,protectionAvailability,protectionUpdates:(rows.results||[]).map(r=>({option_id:r.option_id,policy_id:r.policy_id,task_id:r.task_id,sequence:r.sequence,payload:JSON.parse(r.payload_json),created_at:r.created_at}))};}catch{return {protectionBridgeEnabled:false,protectionUpdates:[],protectionUpdatesUnavailable:true};}}
export async function protectionQueue(opts,owner){if(opts.env.COVERAGEFIT_SMARTDEVICES_ENABLED!=='true')return [];const rows=await opts.db.prepare(`SELECT u.*,json_extract(r.draft_json,'$.contact.name') AS client_name,EXISTS(SELECT 1 FROM cf_recommendation_events e WHERE e.recommendation_id=u.recommendation_id AND e.revision=u.revision AND e.kind='proceed' AND json_extract(e.payload_json,'$.optionId')=u.option_id) AS requested_proceed FROM cf_protection_updates u JOIN cf_recommendations r ON r.id=u.recommendation_id WHERE r.owner_id=?1 AND r.current_revision=u.revision AND NOT EXISTS(SELECT 1 FROM cf_protection_reviews v WHERE v.update_request_id=u.request_id) AND u.sequence=(SELECT MAX(x.sequence) FROM cf_protection_updates x WHERE x.recommendation_id=u.recommendation_id AND x.revision=u.revision AND x.option_id=u.option_id AND x.policy_id=u.policy_id AND x.task_id=u.task_id) ORDER BY requested_proceed DESC,u.created_at DESC LIMIT 100`).bind(owner).all();return (rows.results||[]).map(r=>({recommendationId:r.recommendation_id,optionId:r.option_id,policyId:r.policy_id,taskId:r.task_id,label:PROTECTIONS[r.task_id],clientName:r.client_name,requestedProceed:Boolean(r.requested_proceed),state:JSON.parse(r.payload_json).state,updatedAt:r.created_at}));}
export async function reviewProtection(opts,record,requestId,actor){if(!UUID.test(requestId||''))deviceFail(422,'device_review','Choose an actual customer update.');const r=await opts.db.prepare('SELECT * FROM cf_protection_updates WHERE request_id=?1 AND recommendation_id=?2 AND revision=?3').bind(requestId,record.id,record.current_revision).first();if(!r)deviceFail(409,'device_review','This update is not part of the current recommendation.');const last=await opts.db.prepare(latestSql).bind(record.id,r.revision,r.option_id,r.policy_id,r.task_id).first();if(last.sequence!==r.sequence)deviceFail(409,'device_review','A newer update needs review.');await opts.db.prepare("INSERT OR IGNORE INTO cf_protection_reviews(update_request_id,actor_id,status,created_at) VALUES(?1,?2,'professional-reviewed',?3)").bind(requestId,actor,new Date().toISOString()).run();return {ok:true,reviewStatus:'professional-reviewed',carrierDetermination:'unknown'};}
export async function cleanupProtectionSessions(db){await db.prepare('DELETE FROM cf_protection_sessions WHERE token_hash IN (SELECT token_hash FROM cf_protection_sessions WHERE expires_at<?1 LIMIT 500)').bind(new Date().toISOString()).run();}
